### PR TITLE
TravisCI / Fix container parameters pass

### PR DESCRIPTION
**Pull request by dnsl48**
It looks like when "$NO_BACKUP_RECOVERY" is undefined, thet container.sh doesn't get its parameters right.

### CODE REVIEW

**Comment by FxKu** [comment]
How can I reproduce the issue? Just tried `run.sh` without specifying a second parameter.

**Comment by dnsl48** [comment]
you may need to read the test logs and see that it didn't actually run any tests.
E.g. here: https://travis-ci.org/pgMemento/pgMemento/jobs/513861614
it just ran the container and then shut it down without launching testing scripts.

That's why e.g. the tests that don't skip backup didn't fail here - https://travis-ci.org/pgMemento/pgMemento/builds/513861604

**Comment by FxKu** [comment]
I see, then let's fix the test :)
Wasn't sure if revert_trasnaction is executed twice. You only need to do it after restoring. Use psql -c "SELECT ..." instead of sql file.

**Comment by dnsl48** [comment]
> Use psql -c "SELECT ..." instead of sql file.

Oh, I was specifically going for the file because I wanted to add extra guarantees there with probing state before restoring data from the dump. So, to make sure that the original transaction ids are in place.
```sql
(select max(id) from pgmemento.transaction_log)
```

**Comment by FxKu** [comment]
let's see, if I can fix it quickly ;)

**Pull request merged**
